/* Generated By:JavaCC: Do not edit this line. mozParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface mozParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 9;
  /** RegularExpression Id. */
  int EQ = 10;
  /** RegularExpression Id. */
  int SK = 11;
  /** RegularExpression Id. */
  int SC = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int THEN = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int SEND = 17;
  /** RegularExpression Id. */
  int REC = 18;
  /** RegularExpression Id. */
  int IN = 19;
  /** RegularExpression Id. */
  int END = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int THR = 23;
  /** RegularExpression Id. */
  int PROC = 24;
  /** RegularExpression Id. */
  int CL = 25;
  /** RegularExpression Id. */
  int CR = 26;
  /** RegularExpression Id. */
  int PL = 27;
  /** RegularExpression Id. */
  int PR = 28;
  /** RegularExpression Id. */
  int PORT = 29;
  /** RegularExpression Id. */
  int ID = 30;
  /** RegularExpression Id. */
  int CONSTANT = 31;
  /** RegularExpression Id. */
  int DIGIT = 32;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"let\"",
    "\"=\"",
    "\"skip\"",
    "\";\"",
    "\",\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"send\"",
    "\"receive\"",
    "\"in\"",
    "\"end\"",
    "\"true\"",
    "\"false\"",
    "\"thread\"",
    "\"proc\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"port\"",
    "<ID>",
    "<CONSTANT>",
    "<DIGIT>",
  };

}
